### ISSUE TITLE
Ability to disable for certain URLs

### ISSUE THREAD

**Issue by jswanner** [jswanner/DontFuckWithPaste#3]
There are other uses for `paste` events besides blocking paste, this extension should allow for a whitelist of URLs in which it does not highjack `paste` events.

**Comment by JoshSchreuder** [comment]
:+1: for this suggestion, as the extension currently breaks Imgur and Github image pasting as well.

**Comment by mjball** [comment]
:+1: for the same reason ash @JoshSchreuder.

**Comment by Ancyker** [comment]
:+1: @JoshSchreuder is right, and it's annoying. I've currently disabled it until that's fixed.

Perhaps there's a work around? i.e. if no form is in focus, allow the page to catch the paste event, but if a form is in focus, don't let it? That would at least allow imgur. I didn't really look at how it actually works so I don't know if that's possible or not.

Alternatively, a whitelist is fine as well.

**Comment by cespare** [comment]
Like @kalbasit, I'd prefer a blacklist approach rather than whitelist. (That is, if possible I'd like to click a browser action to disable paste-fuckery.) It's only occasionally that I run into some website that disables password pasting, and I'd rather not have the extension loaded on all websites the rest of the time.

**Comment by thegranddesign** [comment]
@jswanner any progress here? I just found this plugin.  Which is _exactly_ what I'm looking for. What is the easiest, most minimal thing we can do to get something to work?

I'm actually of the opposite opinion of @cespare.  Your plugin basically does nothing and I have no problem running it on every page.  There will be few pages on which this solution causes a problem and I'd prefer not to have to think about it any other time.

**Comment by jswanner** [comment]
@JoshSchreuder, @mjball, @Ancyker: I've pushed a new version of the extension that disables it on facebook.com, github.com, and imgur.com domains.

I would much rather have user-configurable settings, but this is a band-aid to the problem. I'm still waiting for the new version to be published by the Chrome Web Store.

**Comment by thegranddesign** [comment]
@jswanner thank you. This is a decent bandaid. I've never built a plugin before.

**Comment by mjball** [comment]
@jswanner appreciate it! Unfortunately this problem is still a deal-breaker because I use GitHub Enterprise on a separate domain at work :crying_cat_face:

**Comment by thegranddesign** [comment]
@mjball that's why this is a band-aid. ;)

**Comment by jswanner** [comment]
This feature has been added, I'm just waiting for the new version to be published by the Chrome Web Store.
